repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.10
    hooks:
      - id: biome-check
  - repo: https://github.com/lycheeverse/lychee
    rev: lychee-v0.23.0
    hooks:
      - id: lychee
        args:
          - "--offline"
          - "--exclude-path=docs/archive"
          - "--exclude-path=test/archive"
