# config.example.yaml

# set to null or comment out to disable auto-opening
pdf_viewer: xdg-open # or firefox, evince, null, etc

# array of regex patterns to remove shortcodes globally
global_remove_shortcodes:
  - ""

math:
  enabled: true
  engine: katex
  katex_options:
    throwOnError: false
    trust: false
    macros:
      "\\RR": "\\mathbb{R}"

# precedence: --plugins-root > env var > this key > OS default
# plugins_root: "~/.config/oshea/plugins"

# Override settings for any registered or bundled plugin.
# cv:                    # plugin's short-name
#   description:         # "My Custom CV Style"
#   toc_options:         # override plugin's default.yaml
#     enabled: false
#     ...
